### PR TITLE
Add Linting with basic ES17/Expo/React standards

### PR DESCRIPTION
**Pull request by BKreisel**

### CODE REVIEW

**Comment by mnmercer** [comment]
[Add linting](https://trello.com/c/wgs0zEr4/2-add-linting)

**Comment by mnmercer** [comment]
I get an "unmet peer dependency" when I `npm install`.
screen shot 2017-05-24 at 9 27 25 am

**Comment by BKreisel** [comment]
I get the same error. not sure why we're getting that considering it wants React 15+ and we're at 16-alpha. I get the same errors and warnings from the main branch so I'm fairly certain this issue is tied to expo itself.

**Comment by mnmercer** [comment]
@BKreisel Just built `master` and this branch today, opened it up in the Expo mobile app, and I didn't get any errors. I opened up this branch in my iOS simulator and got the errors below. A message saying my version of Expo in the simulator was out of date, but then it disappeared.
screen shot 2017-06-10 at 8 04 11 pm

I think I've seen updates to the Expo app lately that mention support for newer versions of React Native. Potentially it just fixed itself?

**Pull request merged**
